name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: sudo apt install mysql-server
    - run: sudo /etc/init.d/mysql start
    - run: sudo mysql -u root -proot -e "CREATE USER 'solargators'@'localhost' IDENTIFIED BY '';"
    - run: sudo mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'solargators'@'localhost';"
    - run: npm run install-all
    - run: cd backend && npm run create-db && npm run migrate

    # Uncomment this when we've added tests
    # - run: npm test
