name: CI

on: [push]

defaults:
  run:
    working-directory: backend

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: cd ../ && npm ci
    - run: sudo apt install mysql-server
    - run: sudo /etc/init.d/mysql start
    - run: sudo mysql -u root -proot -e "CREATE USER 'solargators'@'localhost' IDENTIFIED BY '';"
    - run: sudo mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'solargators'@'localhost';"
    - run: npm ci --force
    - run: npm run build
    - run: npm run create-db
    - run: npm run migrate

    # Uncomment this when we've added tests
    # - run: npm test
