name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - run: sudo apt-get install nodejs
    - run: sudo apt install mysql-server
    - run: mysql -e "CREATE USER 'solargators'@'localhost' IDENTIFIED BY '';"
